spring:
  datasource:
    url: jdbc:h2:mem:localdb
    driver-class-name: org.h2.Driver
    username: bcnc
    password: bcncpass
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        cache:
          use_second_level_cache: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  h2:
    console:
      enabled: true
      path: /h2-console